name: unit tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        include:
        - python-version: "3.6"
          os: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update black
        if: ${{ matrix.python-version == 3.9 }}
        run: |
            pip install --upgrade black

      - name: Lint and Format Check with flake8 and black
        if: ${{ matrix.python-version == 3.9 }}
        run: |
          black --diff --check .
          flake8

      - name: Update coverage
        if: ${{ matrix.python-version == 3.9 }}
        run: |
          pip install --upgrade coverage

      - name: Basic Test with pytest
        run: |
          PYTHONPATH=. coverage run $(which pytest)

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Basic Test with pytest
        run: |
          PYTHONPATH=. pytest

